apiVersion: v1 # Мы указываем для api сервера, что мы описываем объект из api версии 1
kind: Service # Мы разворачиваем объект типа Сервис
metadata:
  name: svc-nginx-init-dz3 # Имя сервиса
  namespace: dz3
spec:
  ports:
    - name: http-app
      port: 80 # Номер порта, на котором слушает наш сервис
  selector:
    app: web-init # В селекторе указываем лейбл пода, чтобы он его нашел и подключился
